spring:
  application:
    name: notificador

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8


envio:
  email:
    remetente: paulo.jp806@gmail.com
    nomeRemetente: João Paulo Santana

server:
  port: 8082